// components/pricing/plans.ts
export type PlanId = "FREE" | "BASIC" | "PRO";

export type Plan = {
  id: PlanId;
  title: string;
  subtitle: string;
  priceMonthly: number; // 0, 15, 30
  currency: string; // "$"
  highlight?: boolean;
  ctaLabel: string;
  features: string[];
  limits?: string[];
};

export const PLANS: Plan[] = [
  {
    id: "FREE",
    title: "FREE",
    subtitle: "Спробуй систему і звикни до порядку",
    priceMonthly: 0,
    currency: "$",
    ctaLabel: "Почати безкоштовно",
    features: [
      "1 організація (завжди одна)",
      "До 5 клієнтів",
      "До 10 інвойсів",
      "Базові PDF (інвойс/акт)",
      "Todo-лист",
      "Завантаження документів",
    ],
    limits: [
      "Без аналітики",
      "Без експорту CSV/XLSX",
      "Watermark у PDF (“Generated by PBA”)",
      "Ліміт на документи",
    ],
  },
  {
    id: "BASIC",
    title: "BASIC",
    subtitle: "Щоденна робота ФОП без обмежень",
    priceMonthly: 15,
    currency: "$",
    highlight: true,
    ctaLabel: "Обрати BASIC",
    features: [
      "Необмежено клієнтів",
      "Необмежено інвойсів",
      "Статуси інвойсів: Draft / Sent / Paid / Canceled",
      "PDF без watermark",
      "Базова аналітика: дохід + unpaid",
      "Експорт PDF",
    ],
  },
  {
    id: "PRO",
    title: "PRO",
    subtitle: "Максимум контролю, автоматизації і звітності",
    priceMonthly: 30,
    currency: "$",
    ctaLabel: "Обрати PRO",
    features: [
      "Розширена аналітика: місяць/рік, клієнти, середній чек, графік доходу",
      "Авто-нагадування про оплату інвойсів",
      "Авто-нагадування по задачах",
      "Кастомні шаблони PDF (логотип/реквізити/стиль)",
      "Експорт CSV + XLSX",
      "Пріоритетна підтримка",
    ],
  },
];
